<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TlWriter.fs" />
    <Compile Include="TlReader.fs" />
    <Compile Include="Schema.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crypto\Zephyr.Crypto.fsproj" />
  </ItemGroup>

</Project>
